/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modelo.UsuarioModelo;

public class FrmPrincipal extends javax.swing.JFrame {
  
    
    
    public FrmPrincipal() {
        initComponents();
     //   FrmLogin frmlogin = new FrmLogin(this, true);
       // frmlogin.setVisible(true);
     
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_logado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Clientes = new javax.swing.JMenu();
        jMenuItem_CadastrarCliente = new javax.swing.JMenuItem();
        jMenuItem_AlterarCliente = new javax.swing.JMenuItem();
        jMenuItem_ExcluirCliente = new javax.swing.JMenuItem();
        jMenuItem_ConsultarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_logado.setText("1");

        jMenu_Clientes.setText("Clientes");

        jMenuItem_CadastrarCliente.setText("Cadastrar");
        jMenuItem_CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastrarClienteActionPerformed(evt);
            }
        });
        jMenu_Clientes.add(jMenuItem_CadastrarCliente);

        jMenuItem_AlterarCliente.setText("Alterar");
        jMenuItem_AlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AlterarClienteActionPerformed(evt);
            }
        });
        jMenu_Clientes.add(jMenuItem_AlterarCliente);

        jMenuItem_ExcluirCliente.setText("Excluir");
        jMenuItem_ExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ExcluirClienteActionPerformed(evt);
            }
        });
        jMenu_Clientes.add(jMenuItem_ExcluirCliente);

        jMenuItem_ConsultarCliente.setText("Consultar");
        jMenuItem_ConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarClienteActionPerformed(evt);
            }
        });
        jMenu_Clientes.add(jMenuItem_ConsultarCliente);

        jMenuBar1.add(jMenu_Clientes);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(jLabel_logado)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jLabel_logado)
                .addGap(35, 35, 35))
        );

        setSize(new java.awt.Dimension(566, 363));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastrarClienteActionPerformed
        FrmInserirCliente frm = new FrmInserirCliente(this,true);
        frm.usuarioLogado = jLabel_logado.getText();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadastrarClienteActionPerformed

    private void jMenuItem_AlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AlterarClienteActionPerformed
        FrmManipularCliente frm = new FrmManipularCliente(this,true);
        frm.flag = 0;
        frm.usuarioLogado = jLabel_logado.getText();        
        frm.setTitle("Alterar " + frm.getTitle());
        frm.setButton("Alterar");
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem_AlterarClienteActionPerformed

    private void jMenuItem_ExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ExcluirClienteActionPerformed
        FrmManipularCliente frm = new FrmManipularCliente(this,true);
        frm.flag = 1;
        frm.usuarioLogado = jLabel_logado.getText();
        frm.setTitle("Excluir " + frm.getTitle());
        frm.setButton("Excluir");
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ExcluirClienteActionPerformed

    private void jMenuItem_ConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarClienteActionPerformed
        FrmManipularCliente frm = new FrmManipularCliente(this,true);     
        frm.flag = 1;
        frm.usuarioLogado = jLabel_logado.getText();
        frm.setTitle("Consultar " + frm.getTitle());
        frm.setButton("Consultar");
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ConsultarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_logado;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_AlterarCliente;
    private javax.swing.JMenuItem jMenuItem_CadastrarCliente;
    private javax.swing.JMenuItem jMenuItem_ConsultarCliente;
    private javax.swing.JMenuItem jMenuItem_ExcluirCliente;
    private javax.swing.JMenu jMenu_Clientes;
    // End of variables declaration//GEN-END:variables

 public String getUsuario(){
     return jLabel_logado.getText();
 }
    
}
